name: mars-webui
services:  
  searxng:
    container_name: searxng
    networks:
      - mars-network
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID 
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  
  openwebui:
    environment:
        ENABLE_RAG_WEB_SEARCH: True
        RAG_WEB_SEARCH_ENGINE: "searxng"
        RAG_WEB_SEARCH_RESULT_COUNT: 3
        RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
        SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    image: shliakhturov/mars-openwebui:0.6.15_rules_disclaimer_2
    ports:
      - "3000:8080"
    volumes:
      - mars-webui-data:/app/backend/data
      - /srv/share/rules:/app/rules:Z
    networks:
      - mars-network
    pull_policy: if_not_present
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

  sber-wrapper:
    image: shliakhturov/sber-wrapper:add_max2
    ports:
      - "8501:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mars-network
    pull_policy: always
  
  

networks:
  mars-network:
    name: mars-network
    driver: bridge

volumes:
  mars-webui-data:
    name: mars-webui-data
  
  